### ISSUE TITLE
@clerk/nextjs 7.2.8 breaks with e.isFetched' is undefined

### ISSUE THREAD

**Issue by CodingFabian** [clerk/javascript#8428]
After Upgrading 7.2.7 to 7.2.8 our website broke with:

`TypeError: e.isFetched is not a function. (In 'e.isFetched()', 'e.isFetched' is undefined)`

Claude investigated this:

> Root cause: The @clerk/nextjs@7.2.7 → 7.2.8 bump brought in @clerk/shared@4.8.6, which changed its @tanstack/query-core dependency from the exact pin 5.90.16 to the range ^5.90.16. That resolved to 5.100.6, which added isFetched() as a new method on the Query class and has the QueryObserver call query.isFetched().
> 
> Why only production: Clerk's production JS SDK (loaded when __client_uat cookie is present) bundles its own @tanstack/query-core internally (an older version without isFetched()). When @clerk/shared@4.8.6's QueryObserver (from 5.100.6) tries to observe queries from that bundled QueryClient, it calls query.isFetched() on a Query object that doesn't have that method → undefined is not a function.

**Comment by keepforever** [comment]
I experienced the same issue when I bumped as follows:

```sh
@clerk/react-router               ^3.1.7  →    ^3.1.8
```

I also noticed that if I bump react-query deps to `^5.100.6`, while keeping `@clerk/react-router: ^3.1.7`, I get the same error.

```sh
@tanstack/react-query           ^5.100.5  →  ^5.100.6
 @tanstack/react-query-devtools  ^5.100.5  →  ^5.100.6
```

**Comment by jacekradko** [comment]
@CodingFabian Thanks for filing the report. Can you check this again with https://github.com/clerk/javascript/releases/tag/%40clerk%2Fnextjs%407.2.9 ?

**Comment by CodingFabian** [comment]
still the same error on 7.2.9 maybe related to caching since you did seem to solve the underlying issue.

**Comment by vcheeze** [comment]
Can confirm the same error for me when upgrading `@clerk/tanstack-react-start`, although I'm trying to isolate whether this is related to my `@tanstack/react-query` version or not.

**Comment by ipranay** [comment]
Hit this on `@clerk/nextjs@7.2.9` today. Filing a confirmation that 7.2.9 doesn't fully resolve it and our workaround in case it helps others.

## Repro

- `@clerk/nextjs@7.2.9` (latest stable as of writing)
- `@tanstack/react-query@^5.100.6` resolved transitively via `@clerk/shared@4.8.7`'s declared `^5.100.6` peer
- Crash on any component using `useOrganization()` / `useUser()` etc.:

```
TypeError: query.isFetched is not a function
  at QueryObserver.createResult (@tanstack/query-core/build/modern/queryObserver.js:331:24)
  ...
  at useBaseQuery (@clerk/shared/dist/runtime/react/index.mjs:334:55)
  at useClerkQuery (@clerk/shared/dist/runtime/react/index.mjs:372:9)
  at useOrganization (@clerk/shared/dist/runtime/react/index.mjs:1206:18)
```

## What we found

Inspected the runtime `Query` instance from the active Clerk QueryClient in the browser console:

```js
const q = window.Clerk.__internal_queryClient.client.getQueryCache().getAll()[0];
typeof q.isFetched          // → "undefined"
Object.getPrototypeOf(q).constructor.name  // → "k"  (minified Query class from clerk-js CDN bundle)
```

So even on `@clerk/nextjs@7.2.9`, the `Query` instances coming from the **clerk-js CDN bundle** still don't expose `isFetched()` as a method, while the consumer-side `@clerk/shared@4.8.7` resolves `@tanstack/query-core@5.100.7` whose `QueryObserver.createResult` calls `query.isFetched()` at line 327. Same cross-bundle mismatch as the original report — the CDN bundle either hasn't picked up #8432 in our region or is being served from a stale cache.

Bisected `@tanstack/query-core`: the change landed between `5.91.0` (computes inline: `isFetched: newState.dataUpdateCount > 0 || newState.errorUpdateCount > 0`) and `5.91.2` (calls `query.isFetched()`).

## Workaround

Pinned `@tanstack/query-core` to `5.91.0` via yarn `resolutions` to force the consumer-side `QueryObserver` back to the inline computation, which works against any `Query` shape:

```jsonc
// package.json
{
  "dependencies": {
    "@tanstack/react-query": "5.91.0",
    "@tanstack/react-query-devtools": "5.91.0"
  },
  "resolutions": {
    "@tanstack/query-core": "5.91.0"
  }
}
```

This sidesteps the cross-bundle contract entirely — both old and new clerk-js `Query` shapes satisfy the 5.91.0 observer.

Looking forward to the structural fix mentioned in #8432 that moves `QueryClient` ownership into `@clerk/shared`.

**Comment by keepforever** [comment]
Yeah, I'm still getting the `isFetched is not a function` error when I bump to: 

```
"@clerk/react-router": "^3.1.9",
"@tanstack/react-query": "^5.100.7",
```

**Comment by jacekradko** [comment]
We just shipped the latest `clerk-js@6.8.0` which has the `@tanstack/query-core` bump.

**Comment by vcheeze** [comment]
Thanks @jacekradko. Issue is fixed now!
